default: &default
  adapter: postgresql
  encoding: utf8
  pool: 12

development:
  <<: *default
  database: tariff_development
  host: localhost

test:
  <<: *default
  database: tariff_test
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
