name: CI
on: [pull_request]
jobs:
  deploy_dev:
    # needs: [test]
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: "Deploy dev"
        env:
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_SPACE: development
          CF_APP: "tariff-backend-dev"
          CF_APP_WORKER: "tariff-backend-worker-dev"
          CF_APP_XI: "tariff-xi-backend-dev"
          CF_APP_WORKER_XI: "tariff-xi-backend-worker-dev"
          CF_APP_UK: "tariff-uk-backend-dev"
          CF_APP_WORKER_UK: "tariff-uk-backend-worker-dev"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          HEALTHCHECK_URL: ${{ secrets.HEALTHCHECK_URL }}
        run: |
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          cf install-plugin app-autoscaler-plugin -r CF-Community -f
          ./bin/deploy
  deploy_staging:
    needs: [test]
    if: github.ref == 'refs/heads/staging_notyet'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: "Deploy staging"
        env:
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_SPACE: staging
          CF_APP: "tariff-backend-staging"
          CF_APP_WORKER: "tariff-backend-worker-staging"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          HEALTHCHECK_URL: ${{ secrets.HEALTHCHECK_URL }}
        run: |
          curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          cf install-plugin app-autoscaler-plugin -r CF-Community -f
          ./bin/deploy
