name: "E2E Test"
#on: [workflow_dispatch]
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@master
        with:
          repository: TransformCore/trade-tariff-testing
          ref: refs/heads/main
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          env:
            baseUrl: https://www.trade-tariff.service.gov.uk
            services.xi: https://www.trade-tariff.service.gov.uk/xi
            services.uk: https://www.trade-tariff.service.gov.uk/uk
